import FooterComponent from "./components/Footer";
import HeaderComponent from "./components/Header";
import { Work_Sans } from 'next/font/google';
import "./globals.css";


const workSans = Work_Sans({
  subsets: ['latin'], // Subconjuntos de caracteres
  weight: ['400', '600', '700', '900'], // Pesos que quieres cargar
  variable: '--font-work-sans', // Variable CSS para usar en estilos
});

export const metadata = {
  title: "4Print",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className={workSans.variable}>
      <body>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
